#!/bin/bash

# This script sets up a development environment by installing necessary
# libraries, the Rust toolchain, and build essentials.
# It will exit immediately if any command fails.

# This script was partially generated by Gemini 2.5 Pro.

#Author: @haminatorr

set -e

# --- Welcome Message ---
echo "🚀 Starting the development environment setup for your project..."
echo ""

# --- Install System Dependencies ---
echo "--> Step 1: Updating package lists and installing required libraries..."
sudo apt-get update
sudo apt-get install -y \
    build-essential \
    libdbus-1-dev \
    libusb-dev \
    libhidapi-dev \
    libhidapi-hidraw0 \
    pkg-config \
    libudev-dev \
    libgtk-3-dev
echo "✅ System dependencies installed successfully."
echo ""

# --- Install Rust Toolchain ---
echo "--> Step 2: Checking for and installing Rust (if needed)..."
if ! command -v cargo &> /dev/null
then
    echo "Rust not found. Installing the Rust toolchain with 'rustup'..."
    # The '-y' flag accepts all default options for a non-interactive installation
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    
    # Add the cargo binary directory to the current session's PATH
    source "$HOME/.cargo/env"
    
    echo "✅ Rust toolchain installed successfully."
else
    echo "✅ Rust is already installed. Skipping."
fi
echo ""

# --- Finalization and Reboot Prompt ---
echo "🎉 Prerequisites complete!"

# --- Install Razer packages ---
echo "--> Step 3: Installing Razer packages..."
cd razer_control_gui
chmod +x power_state_handler.sh
cp power_state_handler.sh $HOME

./install.sh install

echo "✅ Razer packages installed successfully."
echo ""


echo "A reboot is recommended to ensure all system changes are applied."
echo ""

read -p "Do you want to reboot the system now? (y/n) " -n 1 -r
echo # Move to a new line after the user's input

if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Rebooting system..."
    sudo reboot
else
    echo "Skipping reboot. Please remember to reboot manually later."
fi

exit 0